//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorComprasWCF.ServicoProdutos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/GerenciadorProdutosWCF")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PrecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantidadeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Preco {
            get {
                return this.PrecoField;
            }
            set {
                if ((this.PrecoField.Equals(value) != true)) {
                    this.PrecoField = value;
                    this.RaisePropertyChanged("Preco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantidade {
            get {
                return this.QuantidadeField;
            }
            set {
                if ((this.QuantidadeField.Equals(value) != true)) {
                    this.QuantidadeField = value;
                    this.RaisePropertyChanged("Quantidade");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoProdutos.IServicoGerenciadorProdutos")]
    public interface IServicoGerenciadorProdutos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoGerenciadorProdutos/AdicionarProduto", ReplyAction="http://tempuri.org/IServicoGerenciadorProdutos/AdicionarProdutoResponse")]
        void AdicionarProduto(GerenciadorComprasWCF.ServicoProdutos.Produto value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoGerenciadorProdutos/AdicionarProduto", ReplyAction="http://tempuri.org/IServicoGerenciadorProdutos/AdicionarProdutoResponse")]
        System.Threading.Tasks.Task AdicionarProdutoAsync(GerenciadorComprasWCF.ServicoProdutos.Produto value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoGerenciadorProdutos/EditarProduto", ReplyAction="http://tempuri.org/IServicoGerenciadorProdutos/EditarProdutoResponse")]
        void EditarProduto(GerenciadorComprasWCF.ServicoProdutos.Produto value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoGerenciadorProdutos/EditarProduto", ReplyAction="http://tempuri.org/IServicoGerenciadorProdutos/EditarProdutoResponse")]
        System.Threading.Tasks.Task EditarProdutoAsync(GerenciadorComprasWCF.ServicoProdutos.Produto value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoGerenciadorProdutos/RemoverProduto", ReplyAction="http://tempuri.org/IServicoGerenciadorProdutos/RemoverProdutoResponse")]
        void RemoverProduto(GerenciadorComprasWCF.ServicoProdutos.Produto value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoGerenciadorProdutos/RemoverProduto", ReplyAction="http://tempuri.org/IServicoGerenciadorProdutos/RemoverProdutoResponse")]
        System.Threading.Tasks.Task RemoverProdutoAsync(GerenciadorComprasWCF.ServicoProdutos.Produto value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoGerenciadorProdutos/ObterProdutos", ReplyAction="http://tempuri.org/IServicoGerenciadorProdutos/ObterProdutosResponse")]
        System.Collections.Generic.List<GerenciadorComprasWCF.ServicoProdutos.Produto> ObterProdutos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoGerenciadorProdutos/ObterProdutos", ReplyAction="http://tempuri.org/IServicoGerenciadorProdutos/ObterProdutosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<GerenciadorComprasWCF.ServicoProdutos.Produto>> ObterProdutosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicoGerenciadorProdutosChannel : GerenciadorComprasWCF.ServicoProdutos.IServicoGerenciadorProdutos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoGerenciadorProdutosClient : System.ServiceModel.ClientBase<GerenciadorComprasWCF.ServicoProdutos.IServicoGerenciadorProdutos>, GerenciadorComprasWCF.ServicoProdutos.IServicoGerenciadorProdutos {
        
        public ServicoGerenciadorProdutosClient() {
        }
        
        public ServicoGerenciadorProdutosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoGerenciadorProdutosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoGerenciadorProdutosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoGerenciadorProdutosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AdicionarProduto(GerenciadorComprasWCF.ServicoProdutos.Produto value) {
            base.Channel.AdicionarProduto(value);
        }
        
        public System.Threading.Tasks.Task AdicionarProdutoAsync(GerenciadorComprasWCF.ServicoProdutos.Produto value) {
            return base.Channel.AdicionarProdutoAsync(value);
        }
        
        public void EditarProduto(GerenciadorComprasWCF.ServicoProdutos.Produto value) {
            base.Channel.EditarProduto(value);
        }
        
        public System.Threading.Tasks.Task EditarProdutoAsync(GerenciadorComprasWCF.ServicoProdutos.Produto value) {
            return base.Channel.EditarProdutoAsync(value);
        }
        
        public void RemoverProduto(GerenciadorComprasWCF.ServicoProdutos.Produto value) {
            base.Channel.RemoverProduto(value);
        }
        
        public System.Threading.Tasks.Task RemoverProdutoAsync(GerenciadorComprasWCF.ServicoProdutos.Produto value) {
            return base.Channel.RemoverProdutoAsync(value);
        }
        
        public System.Collections.Generic.List<GerenciadorComprasWCF.ServicoProdutos.Produto> ObterProdutos() {
            return base.Channel.ObterProdutos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<GerenciadorComprasWCF.ServicoProdutos.Produto>> ObterProdutosAsync() {
            return base.Channel.ObterProdutosAsync();
        }
    }
}
